import CreatePost from "./components/CreatePost";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="flex-1 overflow-y-scroll grid grid-cols-12 gap-y-2">{children}</div>
      <CreatePost />
    </>
  );
}
